import { computeKeyId, importSecret, verifyAlias } from "../protocol";

export interface MailiasEnv {
  MAILIAS_SECRET?: string;
  FORWARD_TO?: string;
}

type RuntimeBindings = {
  secret?: string;
  forwardTo?: string;
};

type PageLanguage = "en" | "ja";

const ICON_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128" role="img" aria-label="mailias"><rect width="128" height="128" rx="28" fill="#F6821F"/><path d="M28 30h72a8 8 0 0 1 8 8v34a8 8 0 0 1-8 8H28a8 8 0 0 1-8-8V38a8 8 0 0 1 8-8Z" fill="none" stroke="#fff" stroke-width="8" stroke-linejoin="round"/><path d="m25 38 39 29 39-29" fill="none" stroke="#fff" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><path d="M36 98h50" fill="none" stroke="#fff" stroke-width="9" stroke-linecap="round"/><path d="m79 87 13 11-13 11" fill="none" stroke="#fff" stroke-width="9" stroke-linecap="round" stroke-linejoin="round"/></svg>`;

const SETUP_JS = `const form=document.querySelector("#key-helper");const key=document.querySelector("#recovery-key");const copy=document.querySelector("#copy-key");const status=document.querySelector("#copy-status");const ja=document.documentElement.lang==="ja";form?.addEventListener("submit",event=>event.preventDefault());copy?.addEventListener("click",async()=>{if(!(key instanceof HTMLInputElement)||!key.value){status.textContent=ja?"先にパスワードマネージャーからリカバリーキーを入力してください．":"Enter or autofill the recovery key first.";return;}try{await navigator.clipboard.writeText(key.value);status.textContent=ja?"リカバリーキーをコピーしました．Cloudflare の MAILIAS_SECRET に貼り付けてください．":"Recovery key copied. Paste it into MAILIAS_SECRET in Cloudflare.";}catch{status.textContent=ja?"リカバリーキーをコピーできませんでした．":"Could not copy the recovery key.";}});`;

function json(body: object, status = 200): Response {
  return Response.json(body, {
    status,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Cache-Control": "no-store",
      "Content-Security-Policy": "default-src 'none'; frame-ancestors 'none'",
    },
  });
}

function runtimeBindings(env: MailiasEnv): RuntimeBindings {
  const secret =
    typeof env.MAILIAS_SECRET === "string" && env.MAILIAS_SECRET.length > 0
      ? env.MAILIAS_SECRET
      : undefined;
  const forwardTo =
    typeof env.FORWARD_TO === "string" && env.FORWARD_TO.length > 0
      ? env.FORWARD_TO
      : undefined;
  return { secret, forwardTo };
}

function configuredBindings(bindings: RuntimeBindings): { secret: boolean; forwardTo: boolean } {
  return {
    secret: bindings.secret !== undefined,
    forwardTo: bindings.forwardTo !== undefined,
  };
}

function workerPage(env: MailiasEnv, language: PageLanguage): Response {
  const configured = configuredBindings(runtimeBindings(env));
  const ja = language === "ja";
  const text = ja
    ? {
        title: "mailias Worker セットアップ補助",
        subtitle: "このページは，パスワードマネージャーと Cloudflare の設定画面をつなぐための補助ページです．",
        languageLink: "English",
        languageHref: "/",
        runtimeTitle: "Worker の設定状態",
        configured: "設定済み",
        missing: "未設定",
        openCloudflare: "Cloudflare Workers を開く",
        helperTitle: "リカバリーキーを Cloudflare に設定する",
        helperIntro: "拡張機能のページではパスワードマネージャーが起動しない場合があるため，通常の HTTPS ページであるこの画面を使います．このページが Worker を自動設定することはありません．",
        step1: "新規セットアップなら拡張機能で生成したキーをここに貼り付け，パスワードマネージャーへ保存します．復元時はパスワードマネージャーから自動入力します．",
        step2: "下の「リカバリーキーをコピー」を押します．",
        step3: "Cloudflare で Worker の Settings → Variables and Secrets を開き，MAILIAS_SECRET を Secret として追加して貼り付けます．",
        step4: "FORWARD_TO には転送先メールアドレスを通常の Variable として追加します．これは Secret ではありません．",
        privacy: "ここに入力したリカバリーキーは Worker へ送信されず，mailias にも保存されません．「コピー」を押したときだけブラウザのクリップボードへ書き込みます．",
        entryName: "パスワードマネージャーのエントリ名",
        recoveryKey: "リカバリーキー",
        copy: "リカバリーキーをコピー",
        after: "コピーした値を Cloudflare の MAILIAS_SECRET に貼り付けてください．FORWARD_TO は別途，通常の Variable として設定します．",
      }
    : {
        title: "mailias Worker setup helper",
        subtitle: "This page is a helper that bridges your password manager and the Cloudflare settings page.",
        languageLink: "日本語",
        languageHref: "/ja",
        runtimeTitle: "Worker configuration status",
        configured: "Configured",
        missing: "Missing",
        openCloudflare: "Open Cloudflare Workers",
        helperTitle: "Configure the recovery key in Cloudflare",
        helperIntro: "Password managers do not always work on browser-extension pages, so use this normal HTTPS page instead. This page does not configure the Worker automatically.",
        step1: "For a new setup, paste the key generated by the extension here and save it in your password manager. When restoring, autofill it from your password manager.",
        step2: "Press Copy recovery key below.",
        step3: "In Cloudflare, open Worker Settings → Variables and Secrets, add MAILIAS_SECRET as a Secret, and paste the copied value.",
        step4: "Add FORWARD_TO separately as a normal Variable containing your forwarding email address. It is not a secret.",
        privacy: "The recovery key entered here is never submitted to the Worker or stored by mailias. It is written only to your browser clipboard when you press Copy.",
        entryName: "Password-manager entry name",
        recoveryKey: "Recovery key",
        copy: "Copy recovery key",
        after: "Paste the copied value into MAILIAS_SECRET in Cloudflare. Configure FORWARD_TO separately as a normal Variable.",
      };

  const mark = (ready: boolean) => ready ? text.configured : text.missing;
  const stateClass = (ready: boolean) => ready ? "ok" : "missing";
  const html = `<!doctype html>
<html lang="${language}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${text.title}</title>
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<style>
:root{font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color-scheme:light dark;--orange:#f6821f}*{box-sizing:border-box}body{margin:0;background:Canvas;color:CanvasText}main{width:min(760px,calc(100% - 32px));margin:40px auto 80px}.top{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.brand{display:flex;align-items:center;gap:14px}.brand img{width:48px;height:48px}h1{margin:0;color:var(--orange);font-size:26px}h2{margin:0 0 10px;font-size:18px}p,li{line-height:1.65;color:color-mix(in srgb,CanvasText 72%,transparent)}section{margin-top:24px;padding:20px;border:1px solid color-mix(in srgb,CanvasText 12%,transparent);border-radius:14px;background:color-mix(in srgb,var(--orange) 4%,Canvas)}ol{padding-left:22px}.status-row{display:flex;justify-content:space-between;gap:20px;padding:9px 0;border-top:1px solid color-mix(in srgb,CanvasText 10%,transparent)}.status-row:first-of-type{border-top:0}.ok{color:#237a3b;font-weight:700}.missing{color:#b42318;font-weight:700}label{display:block;margin:14px 0 6px;font-size:13px;font-weight:700}input{width:100%;padding:10px 11px;border:1px solid color-mix(in srgb,CanvasText 24%,transparent);border-radius:8px;background:Field;color:FieldText;font:inherit}button,a.button{display:inline-block;margin-top:12px;padding:9px 12px;border:1px solid var(--orange);border-radius:8px;background:var(--orange);color:white;text-decoration:none;font:inherit;cursor:pointer}.note{font-size:13px}.code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.actions{display:flex;flex-wrap:wrap;gap:8px}.actions .button{margin-top:12px}.secondary{background:transparent!important;color:CanvasText!important;border-color:color-mix(in srgb,CanvasText 22%,transparent)!important}.language-link{font-size:13px;color:var(--orange);text-decoration:none;font-weight:700}#copy-status{min-height:20px;margin-top:8px;font-size:13px}.privacy{padding:12px 14px;border-radius:9px;background:color-mix(in srgb,var(--orange) 10%,Canvas);font-size:13px}@media(max-width:560px){.top{flex-direction:column}.status-row{align-items:flex-start;flex-direction:column;gap:3px}}
</style>
</head>
<body><main>
<div class="top"><div class="brand"><img src="/favicon.svg" alt=""><div><h1>${text.title}</h1><p>${text.subtitle}</p></div></div><a class="language-link" href="${text.languageHref}">${text.languageLink}</a></div>
<section><h2>${text.runtimeTitle}</h2><div class="status-row"><span><span class="code">MAILIAS_SECRET</span> (Secret)</span><span class="${stateClass(configured.secret)}">${mark(configured.secret)}</span></div><div class="status-row"><span><span class="code">FORWARD_TO</span> (Variable)</span><span class="${stateClass(configured.forwardTo)}">${mark(configured.forwardTo)}</span></div><div class="actions"><a class="button" href="https://dash.cloudflare.com/?to=/:account/workers-and-pages" target="_blank" rel="noreferrer">${text.openCloudflare}</a></div></section>
<section><h2>${text.helperTitle}</h2><p>${text.helperIntro}</p><ol><li>${text.step1}</li><li>${text.step2}</li><li>${text.step3}</li><li>${text.step4}</li></ol><p class="privacy"><strong>${text.privacy}</strong></p><form id="key-helper" autocomplete="on"><label for="helper-user">${text.entryName}</label><input id="helper-user" name="username" autocomplete="username" value="mailias recovery key" readonly><label for="recovery-key">${text.recoveryKey}</label><input id="recovery-key" name="password" type="password" autocomplete="current-password"><button id="copy-key" type="button">${text.copy}</button><div id="copy-status" role="status"></div></form><p class="note">${text.after}</p></section>
</main><script src="/setup.js"></script></body></html>`;
  return new Response(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": "no-store",
      "Content-Security-Policy": "default-src 'none'; img-src 'self'; style-src 'unsafe-inline'; script-src 'self'; frame-ancestors 'none'",
      "Referrer-Policy": "no-referrer",
    },
  });
}

function helperScript(): Response {
  return new Response(SETUP_JS, {
    headers: {
      "Content-Type": "text/javascript; charset=utf-8",
      "Cache-Control": "no-store",
      "Content-Security-Policy": "default-src 'none'",
    },
  });
}

function favicon(): Response {
  return new Response(ICON_SVG, {
    headers: {
      "Content-Type": "image/svg+xml; charset=utf-8",
      "Cache-Control": "public, max-age=86400",
      "Content-Security-Policy": "default-src 'none'",
    },
  });
}

async function health(request: Request, env: MailiasEnv): Promise<Response> {
  const url = new URL(request.url);
  const domain = url.searchParams.get("domain");
  const bindings = runtimeBindings(env);
  const configured = configuredBindings(bindings);

  if (!domain || !bindings.secret) {
    return json({ status: "ok", version: "v1", configured, keyId: null });
  }

  try {
    const key = await importSecret(bindings.secret);
    return json({
      status: "ok",
      version: "v1",
      configured,
      keyId: await computeKeyId(key, domain),
    });
  } catch {
    return json({ status: "error", version: "v1", configured, keyId: null }, 500);
  }
}

export default {
  async fetch(request: Request, env: MailiasEnv): Promise<Response> {
    const url = new URL(request.url);
    if (request.method === "GET" && (url.pathname === "/" || url.pathname === "/en")) {
      return workerPage(env, "en");
    }
    if (request.method === "GET" && url.pathname === "/ja") {
      return workerPage(env, "ja");
    }
    if (request.method === "GET" && url.pathname === "/setup.js") {
      return helperScript();
    }
    if (request.method === "GET" && url.pathname === "/favicon.svg") {
      return favicon();
    }
    if (request.method === "GET" && url.pathname === "/health") {
      return health(request, env);
    }
    return new Response("Not found", { status: 404 });
  },

  async email(message: ForwardableEmailMessage, env: MailiasEnv): Promise<void> {
    const bindings = runtimeBindings(env);
    if (!bindings.secret || !bindings.forwardTo) {
      console.error(JSON.stringify({ event: "mailias_email_unconfigured" }));
      return;
    }

    try {
      const key = await importSecret(bindings.secret);
      const valid = await verifyAlias(key, message.to);
      console.log(JSON.stringify({ event: "mailias_alias_verification", valid }));
      if (!valid) return;

      console.log(JSON.stringify({ event: "mailias_email_forward_start" }));
      await message.forward(bindings.forwardTo);
      console.log(JSON.stringify({ event: "mailias_email_forward_success" }));
    } catch (error) {
      console.error("mailias email handling failed", error);
      throw error;
    }
  },
} satisfies ExportedHandler<MailiasEnv>;
